name: segan-py36
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python==3.6.8
  - scipy==1.1.0
  - librosa==0.6.1
  - h5py==2.8.0
  - numba==0.38.0
  - pytorch==1.5.1 
  - torchvision==0.6.1 
  - matplotlib==2.2.2
  - numpy==1.14.3
  - pyfftw==0.10.4
  - tensorboardX==1.4
pip:
  - SoundFile==0.10.2